server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2_db
    username: skymoonight
    password: ENC(AfBfbm5sT3vOa6CAhdIPaKGSBs4xAgO7)