server:
  port: 443
#  443
  ssl:
    enabled: true
    key-store: classpath:cert.jks
    key-password: seleuchel
    key-store-type: JKS
    key-alias: 1

    trust-store: classpath:trustcert.jks
    trust-store-password: seleuchel
    protocol: TLS
    client-auth: want

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2_db
  security:
    user:
      name: skymoonight
      password: ENC(ofUO3GOYyufVWXXmFNdTOlbhEk78aQfn)
##      password: ddorddor

security.jwt.token.secret-key: skymoonight
security.jwt.token.expire-length: 3600000

jasypt:
  encryptor:
    password: test1234
    property:
      prefix: ENC(
      suffix: )
#    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
#    bean: jasyptStringEncryptor